In [3]:
import pandas as pd
import numpy as np

In [10]:
df = pd.read_csv('data/courses.csv')
df

,subj,num,suf,format,term,code,inst,title,sec,enr
0,NEJS,188,A,LEC,Fall 2004,1043,"Levy, Avigdor",RISE/DECLINE:OTTOMAN EMP,1,32
1,CHEM,121,A,LEC,Fall 2004,1043,"Foxman, Bruce","INORGANIC CHEM I, LECS.",1,18
2,CHEM,130,A,LEC,Fall 2004,1043,"Yu, Jinquan",ADV ORG. CHEM: STRUCTURE,1,14
3,COMP,1,A,LEC,Fall 2004,1043,"Ruesch, Gordon",COMPOSITION,3,11
4,MUS,118,A,STD,Fall 2004,1043,"Ray, Mary",SENIOR RECITAL I,1,3
...,...,...,...,...,...,...,...,...,...,...
35201,BIOL,26,A,LEC,Summer 2021,1212,"Kosinski-Collins, Melissa",Plant Biology,1,9
35202,ECON,28,B,LEC,Summer 2021,1212,"AlMehdar, Mohammed",The Global Economy,1,4
35203,PHIL,1,A,LEC,Summer 2021,1212,"Lupu, Peter",Introduction to Philosophy,1,3
35204,AAAS,160,B,LEC,Summer 2021,1212,"Plumb, Betsy Loren",If We Must Die: War and Military Service in Af...,1,3
35205,IGS,130,A,LEC,Summer 2021,1212,"Campion, Selene",Global Migration,1,1

In [20]:
#pt = df.pivot_table(df,index='code',values='enr',columns='subj',aggfunc=np.sum)
df[df['term']=='Spring 2021'].groupby('subj')['enr'].agg(np.sum).sort_values().tail(10)

subj
ANTH     579
HWL      749
MATH     786
PSYC     823
COSI     918
CHEM    1020
ECON    1110
BIOL    1222
BUS     1264
HS      2395
Name: enr, dtype: int64